# Generated by Django 2.2.11 on 2022-01-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clone',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
